package:
  name: metagraph-numba
  version: {{ environ.get('GIT_DESCRIBE_TAG', 'unknown') }}

source:
  path: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)|int }}
  string: py_{{GIT_DESCRIBE_HASH}}_{{ GIT_DESCRIBE_NUMBER }}
  script: python setup.py install --single-version-externally-managed --record=record.txt
  noarch: python

requirements:
  host:
    - python

  run:
    - python
    - numba
    - metagraph >=0.2.4

test:
  requires:
    - pytest
    - pytest-cov
    - coverage
    - scikit-learn  # for metagraph

  commands:
    - pytest --pyargs metagraph_numba.tests
    - pytest --pyargs metagraph.tests

about:
  home: https://github.com/metagraph-dev/metagraph-numba
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: 'Metagraph plugin for the Numba compiler'
  description: |
      Plugin for metagraph to use the Numba compiler
  dev_url: https://github.com/metagraph-dev/metagraph-numba
